
import "./globals.scss";
import "rsuite/dist/rsuite.min.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Inter } from "next/font/google";
import { Footer, Header, CustomLoader } from "@Components";
import { Providers, ThemeProvider } from "@Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type LocaleLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

const locales = ['en', 'es'];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <Providers>
            <div className="min-h-screen">
              <CustomLoader />
              <Header />
              <div>{children}</div>
              <Footer />
            </div>
          </Providers>
        </body>
      </ThemeProvider>
    </html>
  );
}
