import {
  camera1,
  camera2,
  mouse1,
  mouse2,
  mouse3,
  camera3,
  head1,
  head2,
  head3,
  thermo1,
  xbox1,
  xbox2,
  xbox3,
  speaker1,
  speaker2,
  speaker3,
  fitbit1,
  fitbit2,
  fitbit3,
  tv1,
  tv2,
  tv3,
  eco1,
  eco2,
  eco3,
  wifiRouter1,
  wifiRouter2,
  wifiRouter3,
  soundbar1,
  soundbar2,
  soundbar3,
  ps52,
  ps53,
  ps5,
  procam1,
  procam2,
  procam3,
  drone1,
  drone2,
  drone3,
  Curvetv2,
  Curvetv3,
  Curvetv1,
  watch2,
  watch3,
  watch1,
  wirelesshead1,
  wirelesshead2,
  wirelesshead3,
  laptop1,
  laptop2,
  laptop3,
  phone1,
  phone2,
  phone3,
  sdk1,
  sdk2,
  sdk3,
} from "@products";
export const dataex = [
  {
    productName: "Samsung Galaxy S21 Smartphone",
    image: [phone1, phone2, phone3],
    ID: 1,
    description:
      "Experience the latest in technology with the Samsung Galaxy S21 Smartphone. With an AMOLED display, powerful camera system, and 5G capabilities, this smartphone redefines mobile communication.",
    price: 899.99,
    rating: 2.7,
  },
  {
    productName: "HP ProBook X360 Laptop",

    image: [laptop1, laptop2, laptop3],
    ID: 2,
    description:
      "Enhance your productivity with the HP ProBook X360 Laptop. This versatile 2-in-1 laptop features a touch screen, powerful processor, and long-lasting battery, making it perfect for work and entertainment.",
    price: 1099.0,
    rating: 3.6,
  },
  {
    productName: "Wireless Earbuds",

    image: [wirelesshead1, wirelesshead2, wirelesshead3],
    ID: 3,
    description:
      "Immerse yourself in music with these Wireless Earbuds. These earbuds offer noise cancellation and superior sound quality, making them an essential accessory for music lovers.",
    price: 249.99,
    rating: 5,
  },
  {
    productName: "4K Smart TV QLED Q80",

    image: [tv1, tv2, tv3],
    ID: 4,
    description:
      "Elevate your entertainment experience with the 4K Smart TV QLED Q80. Enjoy stunning visuals, vibrant colors, and intelligent features that let you enjoy your favorite content like never before.",
    price: 1499.0,
    rating: 4,
  },
  {
    productName: "PlayStation 5 Gaming Console",
    image: [ps5, ps52, ps53],
    ID: 5,
    description:
      "Enter the immersive world of gaming with the PlayStation 5 Gaming Console. Unleash the power of next-generation graphics, ultra-fast loading times, and a library of entertaining games that will keep you engaged for hours.",
    price: 499.99,
    rating: 5,
  },
  {
    productName: "Smart Health Watch",
    image: [watch1, watch2, watch3],
    ID: 6,
    description:
      "Stay connected to your health with the Smart Health Watch. This intelligent watch features health monitoring features, customizable watch faces, and seamless integration with your phone.",
    price: 299.0,
    rating: 4.5,
  },
  {
    productName: "Canon EOS R6 Mirrorless Camera",
    image: [procam1, procam2, procam3],
    ID: 7,
    description:
      "Capture life's moments in stunning detail with the Canon EOS R6 Mirrorless Camera. This professional camera offers high-resolution images, low-light performance, and advanced autofocus capabilities.",
    price: 2499.0,
    rating: 4.8,
  },
  {
    productName: "Home Theater Soundbar 500",
    image: [soundbar1, soundbar2, soundbar3],
    ID: 8,
    description:
      "Transform your living room into a cinematic experience with the Home Theater Soundbar 500. Enjoy immersive sound, wireless connectivity, and a sleek design that complements your entertainment setup.",
    price: 799.0,
    rating: 4.6,
  },
  {
    productName: "Amazon Echo Dot 4th Gen Smart Speaker",
    image: [eco1, eco2, eco3],
    ID: 9,
    description:
      "Make your home smarter with the Amazon Echo Dot 4th Gen Smart Speaker. Control your smart devices, play music, and get answers with voice commands. Its compact design blends seamlessly into any room.",
    price: 49.99,
    rating: 4.7,
  },
  {
    productName: "DJI Mavic Air 2 Drone",
    image: [drone1, drone2, drone3],
    ID: 10,
    description:
      "Explore the skies and capture breathtaking photos with the DJI Mavic Air 2 Drone. This drone features advanced camera technology, intelligent flight modes, and extended flight time for unforgettable adventures.",
    price: 799.0,
    rating: 4.8,
  },
  {
    productName: "Wireless WiFi 6 Router",
    image: [wifiRouter1, wifiRouter2, wifiRouter3],
    ID: 11,
    description:
      "Experience blazing-fast internet speeds with the Wireless WiFi 6 Router. This router supports the latest WiFi 6 standard, providing reliable connectivity for all your devices and ensuring smooth streaming and online gaming.",
    price: 149.99,
    rating: 4.6,
  },
  {
    productName: "Portable External SSD Drive",
    image: [sdk1, sdk2, sdk3],
    ID: 12,
    description:
      "Take your data on the go with the Portable External SSD Drive. This compact drive offers ample space for your files, whether you're working, traveling, or storing important data.",
    price: 179.0,
    rating: 4.7,
  },
  {
    productName: "Fitbit Charge 4 Health Tracker",
    image: [fitbit1, fitbit2, fitbit3],
    ID: 13,
    description:
      "Track your physical fitness journey with the Fitbit Charge 4 Health Tracker. Monitor your heart rate, track your workouts, and analyze your sleep patterns. Its sleek design and long-lasting battery make it an essential accessory.",
    price: 129.95,
    rating: 4.5,
  },
  {
    productName: "Portable Bluetooth Speaker",
    image: [speaker1, speaker2, speaker3],
    ID: 14,
    description:
      "Take your favorite music with you anywhere with the Portable Bluetooth Speaker. This speaker offers impressive sound quality, supports wireless audio streaming, and has a design that keeps it moving forward.",
    price: 69.99,
    rating: 4.4,
  },
  {
    productName: "Ultrawide Curved Monitor",
    image: [Curvetv1, Curvetv2, Curvetv3],
    ID: 15,
    description:
      "Enhance your productivity and entertainment with the Ultrawide Curved Monitor. Immerse yourself in a wide and vibrant display, perfect for multitasking, gaming, and movie-watching.",
    price: 599.0,
    rating: 4.6,
  },
  {
    productName: "Wireless Gaming Mouse",
    image: [mouse1, mouse2, mouse3],
    ID: 16,
    description:
      "Achieve precision and control in games with the Wireless Gaming Mouse. This mouse features customizable buttons, high DPI sensitivity, and an ergonomic design to enhance your gaming experience.",
    price: 79.99,
    rating: 4.7,
  },
  {
    productName: "Noise-Canceling Headphones",
    image: [head1, head2, head3],
    ID: 17,
    description:
      "Escape into your own world with Noise-Canceling Headphones. Enjoy immersive audio quality, block out distractions, and experience ultimate comfort during long audio sessions or while traveling.",
    price: 299.0,
    rating: 4.8,
  },
  {
    productName: "Nest Learning Thermostat",
    image: [thermo1],
    ID: 18,
    description:
      "Optimize energy efficiency in your home with the Nest Learning Thermostat. This thermostat learns your preferences, adjusts the temperature accordingly, and helps you save on energy costs.",
    price: 249.99,
    rating: 4.5,
  },
  {
    productName: "Compact Digital Camera",
    image: [camera1, camera2, camera3],
    ID: 19,
    description:
      "Capture moments on the go with the Compact Digital Camera. This camera offers a balance between portability and image quality, making it a great choice for travel, events, and everyday moments.",
    price: 299.0,
    rating: 4.3,
  },
  {
    productName: "Xbox Series X",
    image: [xbox1, xbox2, xbox3],
    ID: 20,
    description:
      "The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power, DirectX ray tracing, a custom SSD, and 4K gaming.*",
    price: 599.0,
    rating: 5,
  },
];
